import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

/**
 * Public, visitor-facing changelog. One entry per released version, bilingual.
 * Rendered on the discrete /changelog page. Kept separate from the technical
 * CHANGELOG.md (generated by semantic-release from Conventional Commits).
 */
const changelog = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/changelog' }),
  schema: z.object({
    version: z.string(),
    date: z.coerce.date(),
    kind: z.enum(['feature', 'improvement', 'fix']).default('improvement'),
    title: z.object({ fr: z.string(), en: z.string(), nl: z.string() }),
    notes: z.object({
      fr: z.array(z.string()),
      en: z.array(z.string()),
      nl: z.array(z.string()),
    }),
  }),
});

export const collections = { changelog };
